### ISSUE TITLE
Pictures of Players

### ISSUE THREAD

**Issue by Gollwu** [Gollwu/LoLManager#13]

**Comment by Sowerdski** [comment]
Is there a specified format for these pictures?

**Comment by Sowerdski** [comment]
And by the way, which players will be selected?

**Comment by Gollwu** [comment]
For now, just the 10 players in the database (old Alliance Roster and old HT Roster). The goal is mainly to have a template picture on which we can copy the face of the players. Wanna try this? else I'll take care of it this evening

**Comment by Sowerdski** [comment]
I'll try this, I'm planning on saving all pictures in .png format with a 256x256 size

**Comment by Gollwu** [comment]
The pictures are on the repo. Could you also please put the background image in the same format in the folder? And why is Nerevar displayed with a different background?

To the others : Please provide feedback :)

**Comment by Sowerdski** [comment]
Actually there is no predefined background, this is just basic picture cropping, i'll work on it this evening

**Comment by Gollwu** [comment]
You made a little mistake by putting Tabzz instead of Rekkles, the database is already filled with Rekkles so could you please send me the image with rekkles ?

**Comment by Gollwu** [comment]
I close that for now, we'll think about the pictures for further milestones
