### ISSUE TITLE
ORM database and Hosting

### ISSUE THREAD

**Issue by Gollwu** [Gollwu/LoLManager#2]
Current plans for hosting of the application and the database :

Heroku and PostGreSQL
ORM with SequelizeJS (http://sequelizejs.com/articles/heroku)
Exchanges with Client with sockets and Node.js?

Please discuss :)

**Comment by Gollwu** [comment]
I just Created a project (LoLManager-Server) by copying an old project of mine with a database and sockets. I was wondering if we were needing two projects or if it would be better to have both in the same project

**Comment by qr7hur** [comment]
I vote for 1 project.

**Comment by Gollwu** [comment]
About the database, I'm currently using a PostgreSQL database provided by Hoerku but a collegue of mine recommended me to use a MongoDB database (also provided by Heroku). He told me that it was better because mongo was throwing JSON for results (and we are using javascript). Any thoughts on that?
