### ISSUE TITLE
Update turret asset when they take damage

### ISSUE THREAD

**Issue by Gollwu** [Gollwu/LoLManager#25]

**Comment by Gollwu** [comment]
Waiting for assets to test but done

**Comment by Sowerdski** [comment]
Do you have an idea about when the nexus and inhibs assets will be needed?

**Comment by Gollwu** [comment]
Well I'm currently working on the code where the players push the turrets and I'm already implementing the push of inhibitors and nexus. So when you want. It's still not urgent

**Comment by Gollwu** [comment]
Working as intended with pushing of inhis and Nexus and win condition if Nexus.HP < 0 launching an alert telling which team won.
