### ISSUE TITLE
Cannot find readable-stream/transform

### ISSUE THREAD

**Issue by Nhacsam** [Gollwu/LoLManager#47]
Continue of the #45 discussion of a problem with the Gollwu's npm install.
Last Comment of Gollwu : 

npm install gives 'images' errored after 65ms. Cannot find readable-stream/transform (whatever I already got this error with countless other dependency I installed them all it changed nothing and I can't install this one with npm install readable-stream/transform)

1.4.28 for my version. May be the problem indeed ? That's a good remark

**Comment by Nhacsam** [comment]
I have the 1.3.10. I don't think it's a problem of version.
You can install the missing package with `npm install readable-stream` but I want to understand why you had this problem.

Can you restart form zero and make : 

```
mv node_modules/ node_modules_bak
npm install
```

And give me the content of `npm-debug.log`. You can create a Gist or use pastebin.

**Comment by Gollwu** [comment]
"You can install the missing package with npm install readable-stream". No that's my point, this one doesn't work, I would have done it. It says it doesn't find it (I'll copy the stack trace this evening and I'll do what you advised this eening also),

**Comment by Gollwu** [comment]
Problem solved. As you asked I removed everything from my node_modules ad restarted everything. The problem was that I did not start my cmd as admin. I still had to npm install bower manually to run the main npm install.

Thx :)
