### ISSUE TITLE
Sketch interface screens

### ISSUE THREAD

**Issue by qr7hur** [Gollwu/LoLManager#7]
My original question was:
_what are the smallest increments that we need in order to transform the "thing" we have now into a game?_

But it's too open so let's get some visual hints that will give us ideas about what should happen in the code.

Example?

![sketch1](https://cloud.githubusercontent.com/assets/9404278/6180505/d650d0d0-b2f3-11e4-806a-46eebd29b805.png)

Feel free to edit / add details / translate to code/architecture suggestion

**Comment by Gollwu** [comment]
Well the first step to make it a game is the game engine.If we create a small A.I to compete with the game could already be fun :)
