### ISSUE TITLE
Type of the game

### ISSUE THREAD

**Issue by Gollwu** [Gollwu/LoLManager#8]
Another important question still to be answered and which would be nice to answer before going to far in the project is the kind of game we want to do.

There are around 3 good possibilities : 
- Local game where the player has its own db locally on the computer and plays alone
- Internet-based with one big server and all the teams trying to get into LCS?
- Several little servers with around 60 Teams(?) 

We of course have to see which one is the most fun and what we can do...

**Comment by Nhacsam** [comment]
Mobile App with famo.us ;)
https://www.youtube.com/watch?v=EjLCfD8qrkE
